name: Hexo Build and Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate static files
        run: npx hexo generate

      - name: Deploy to GitHub Pages
        env:
          GIT_DEPLOY_TOKEN: ${{ secrets.DEPLOY_KEY }}
        run: |
          git config --global user.name "asdofe"
          git config --global user.email "asdofe"@gmail.com

          # 修改 repo url 加入 token 做 auth
          REPO_URL=https://x-access-token:${GIT_DEPLOY_TOKEN}@github.com/${{ github.repository }}.git
          npx hexo deploy --repo "$REPO_URL"
